apiVersion: v1
kind: Secret
metadata:
  labels:
    app: cyberchef
    app.kubernetes.io/part-of: ref-solutions
    layer: tools
  name: cyberchef-generic-webhook
type: Opaque
data:
  WebHookSecretKey: MDM0YmJhNDM0YTY5NDc0Yg==
