apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: reverseshellgenerator
  namespace: {{ .Value.namespace }}
  labels:
    app: reverseshellgenerator
    app.kubernetes.io/component: {{ .Value.name }}
    layer: tools
  annotations:
    uri-official: https://github.com/0dayCTF/reverse-shell-generator.git
spec:
  lookupPolicy:
    local: false
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/fernando0069-dev/reverseshellgenerator:latest
    generation: 6
    importPolicy:
      importMode: Legacy
    referencePolicy:
      type: Source