apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: reverseshellgenerator
  namespace: fernando0069-dev
  labels:
    app: reverseshellgenerator
    app.kubernetes.io/component: reverseshellgenerator
    app.kubernetes.io/part-of: ref-solutions
    layer: tools
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: reverseshellgenerator
