apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
spec:
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: reverseshellgenerator
    weight: 100
  wildcardPolicy: None
