apiVersion: v1
kind: Secret
metadata:
  labels:
    app: reverseshellgenerator
    app.kubernetes.io/part-of: ref-solutions
    layer: tools
  name: reverseshellgenerator-github-webhook
type: Opaque
data:
  WebHookSecretKey: NDc1OTZmZWFhY2NhMGM3Mg==
