apiVersion: v1
kind: Secret
metadata:
  labels:
    app: reverseshellgenerator
    app.kubernetes.io/part-of: ref-solutions
    layer: tools
  name: reverseshellgenerator-generic-webhook
type: Opaque
data:
  WebHookSecretKey: OTY0NzUwMWQxY2U4ZWIwZg==
