apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-generic-webhook
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.enviroment }}
    layer: {{ .Values.layer }}
type: Opaque
data:
  WebHookSecretKey: OTY0NzUwMWQxY2U4ZWIwZg==
