# Default values for buildachart.
# This is a YAML-formatted file.

namespace: fernando0069-dev
name: web-status
labels:
  enviroment: pro
  layer: tools
replicaCount: 1
image: image-registry.openshift-image-registry.svc:5000/fernando0069-dev/web-status:latest
imagePullPolicy: Always
ports:
  http:
    name: http
    containerPort: 8080
    protocol: TCP
    servicePort: 8080
git:
  uri: 'https://github.com/Fernando0069/my-charts.git'
  ref: main
  contextDir: apps/web-status/app/