apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-ear
  namespace: fernando0069-dev
spec:
  steps:
    - computeResources: {}
      image: maven:3.9-eclipse-temurin-21
      name: maven-ear
      script: |
        #!/bin/sh
        set -e
        cd $(workspaces.source.path)/my-charts/charts/files/helloworld_ear
        mvn clean package
        mv target/helloworld.ear . 
        rm -rf target/
  workspaces:
    - name: source