apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-war
  namespace: fernando0069-dev
spec:
  steps:
    - computeResources: {}
      image: maven:3.9-eclipse-temurin-21
      name: maven-war
      script: |
        #!/bin/sh
        set -e
        ls -lR  $(workspaces.source.path)/my-charts/charts/files/helloworld_war
        cd $(workspaces.source.path)/my-charts/charts/files/helloworld_war
        mvn clean package
        ls -lR  $(workspaces.source.path)/my-charts/charts/files/helloworld_war
        mv target/helloworld.war . 
        rm -rf target/
        ls -lR  $(workspaces.source.path)/my-charts/charts/files/helloworld_war
  workspaces:
    - name: source