apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-push
  namespace: fernando0069-dev
spec:
  params:
    - name: git-user
      type: string
    - name: git-email
      type: string
  steps:
    - image: alpine/git
      name: push
      script: |
        #!/bin/sh
        set -e
        cd $(workspaces.source.path)/my-charts
        git config --global user.name "$(params.git-user)"
        git config --global user.email "$(params.git-email)"
        git add .
        git commit -m "Actualización automática del Chart"
        git push origin main
  workspaces:
    - name: source