#### update-gh-pages

Hay que eliminar la rama "gh-pages" y luego recrearla.

```
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: update-gh-pages
  namespace: fernando0069-dev
spec:
  params:
    - name: git-user
      type: string
    - name: git-email
      type: string
  steps:
    - image: alpine/git
      name: reset
      script: |
        #!/bin/sh
        set -e
        cd $(workspaces.source.path)/my-charts

        # Configurar usuario de Git
        git config --global user.name "$(params.git-user)"
        git config --global user.email "$(params.git-email)"

        # Verificar si la rama gh-pages existe
        if git rev-parse --verify origin/gh-pages >/dev/null 2>&1; then
          git checkout gh-pages
          git rm -rf .
        else
          git checkout --orphan gh-pages
        fi

        # Confirmar y hacer push de la rama limpia
        git commit --allow-empty -m "Reiniciando gh-pages"
        git push origin gh-pages --force
  workspaces:
    - name: source
```