apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
  annotations:
    uri-official: {{ .Values.annotations.uriofficial }}
spec:
  failedBuildsHistoryLimit: 5
  successfulBuildsHistoryLimit: 5
  nodeSelector: null
  postCommit: {}
  runPolicy: Serial
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
  source:
    type: Git
    git:
      uri: {{ .Values.git.uri }}
      ref: {{ .Values.git.ref }}
    contextDir: {{ .Values.git.contextDir }}
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.name }}:latest
  triggers:
  - generic:
      secretReference:
        name: {{ .Values.name }}-generic-webhook
    type: Generic
  - github:
      secretReference:
        name: {{ .Values.name }}-github-webhook
    type: GitHub
  - type: ConfigChange
