apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-generic-webhook
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
  annotations:
    uri-official: {{ .Values.annotations.uriofficial }}
type: Opaque
data:
  WebHookSecretKey: MDM0YmJhNDM0YTY5NDc0Yg==
