apiVersion: v1
kind: Secret
metadata:
  labels:
    app: cyberchef
    app.kubernetes.io/part-of: ref-solutions
    layer: tools
  name: cyberchef-github-webhook
type: Opaque
data:
  WebHookSecretKey: MDY3NTk0ZjMzYjczMjRhYw==
