apiVersion: v1
kind: Service
metadata:
  labels:
    app: cyberchef
    app.kubernetes.io/part-of: ref-solutions
    layer: tools
  name: cyberchef
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: cyberchef
    deployment: cyberchef
  sessionAffinity: None
  type: ClusterIP
