apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-github-webhook
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
  annotations:
    uri-official: {{ .Values.annotations.uriofficial }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: {{ .Values.ports.name }}
    port: {{ .Values.ports.servicePort }}
    protocol: {{ .Values.ports.protocol }}
    targetPort: {{ .Values.ports.containerPort }}
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: {{ .Values.name }}
  sessionAffinity: None
  type: ClusterIP
