# Default values for buildachart.
# This is a YAML-formatted file.

namespace: fernando0069-dev
name: alges-escapade
labels:
  enviroment: pro
  layer: training
  training: DO180
replicaCount: 1
image: image-registry.openshift-image-registry.svc:5000/fernando0069-dev/alges-escapade:latest
imagePullPolicy: Always
ports:
  http:
    name: http
    containerPort: 8080
    protocol: TCP
    servicePort: 8080
git:
  uri: 'https://github.com/Fernando0069/my-charts.git'
  ref: main
  contextDir: apps/do180-alges-escapade/app/src
