kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.enviroment }}
    layer: {{ .Values.layer }}
spec:
  selector:
    matchLabels:
      deployment: {{ .Chart.Name }}
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  scaleTargetRef:
    kind: Deployment
    name: {{ .Chart.Name }}
    apiVersion: apps/v1
  minReplicas: {{ .Values.replica.min }}
  maxReplicas: {{ .Values.replica.max }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.metrics.utilization.cpu }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.metrics.utilization.mem }}
