apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/part-of: ref-solutions
    app.kubernetes.io/managed-by: Helm
    helm.chart-version: {{ .Chart.Name }}-{{ .Chart.Version }}
    helm.app-version: {{ .Chart.Name }}-{{ .Chart.AppVersion }}
    info.layer: {{ .Values.info.layer }}
data:
  00-virtualhost.conf: |
    <VirtualHost *:8080>
        ServerName localhost
        DocumentRoot /var/www/html
        <Directory "/var/www/html">
            Options Indexes FollowSymLinks
            AllowOverride All
            Require all granted
        </Directory>

        # Activa el motor de reescritura
        RewriteEngine On

        # Redirige todas las rutas bajo /cyberchef hacia el servicio backend
        RewriteRule ^/cyberchef(.*)$ http://cyberchef:8080$1 [P]

        # Configuración de ProxyPass y ProxyPassReverse para cyberchef
        ProxyPass /cyberchef/ http://cyberchef:8080/
        ProxyPassReverse /cyberchef/ http://cyberchef:8080/

        # Filtro y reescritura de URLs para /cyberchef
        <Location /cyberchef/>
            ProxyPassReverse /
            RequestHeader unset Accept-Encoding
        </Location>

        # Logs (opcional, para depuración)
        ErrorLog /var/log/httpd/cyberchef-error.log
        CustomLog /var/log/httpd/cyberchef-access.log combined
    </VirtualHost>
  01-ssl.conf: |
    DATE FILE
  file2.txt: |
    Hello\n FILE2.TXT
  health: |
    OK
  httpd.conf: "#\n# This is the main Apache HTTP server configuration file.  It contains
    the\n# configuration directives that give the server its instructions.\n# See
    <URL:http://httpd.apache.org/docs/2.4/> for detailed information.\n# In particular,
    see \n# <URL:http://httpd.apache.org/docs/2.4/mod/directives.html>\n# for a discussion
    of each configuration directive.\n#\n# See the httpd.conf(5) man page for more
    information on this configuration,\n# and httpd.service(8) on using and configuring
    the httpd service.\n#\n# Do NOT simply read the instructions in here without understanding\n#
    what they do.  They're here only as hints or reminders.  If you are unsure\n#
    consult the online docs. You have been warned.  \n#\n# Configuration and logfile
    names: If the filenames you specify for many\n# of the server's control files
    begin with \"/\" (or \"drive:/\" for Win32), the\n# server will use that explicit
    path.  If the filenames do *not* begin\n# with \"/\", the value of ServerRoot
    is prepended -- so 'log/access_log'\n# with ServerRoot set to '/www' will be interpreted
    by the\n# server as '/www/log/access_log', where as '/log/access_log' will be\n#
    interpreted as '/log/access_log'.\n\n#\n# ServerRoot: The top of the directory
    tree under which the server's\n# configuration, error, and log files are kept.\n#\n#
    Do not add a slash at the end of the directory path.  If you point\n# ServerRoot
    at a non-local disk, be sure to specify a local disk on the\n# Mutex directive,
    if file-based mutexes are used.  If you wish to share the\n# same ServerRoot for
    multiple httpd daemons, you will need to change at\n# least PidFile.\n#\nServerRoot
    \"/etc/httpd\"\n\n#\n# Listen: Allows you to bind Apache to specific IP addresses
    and/or\n# ports, instead of the default. See also the <VirtualHost>\n# directive.\n#\n#
    Change this to Listen on a specific IP address, but note that if\n# httpd.service
    is enabled to run at boot time, the address may not be\n# available when the service
    starts.  See the httpd.service(8) man\n# page for more information.\n#\n#Listen
    12.34.56.78:80\nListen 0.0.0.0:8080\n\n#\n# Dynamic Shared Object (DSO) Support\n#\n#
    To be able to use the functionality of a module which was built as a DSO you\n#
    have to place corresponding `LoadModule' lines at this location so the\n# directives
    contained in it are actually available _before_ they are used.\n# Statically compiled
    modules (those listed by `httpd -l') do not need\n# to be loaded here.\n#\n# Example:\n#
    LoadModule foo_module modules/mod_foo.so\n#\nInclude conf.modules.d/*.conf\n\n#\n#
    If you wish httpd to run as a different user or group, you must run\n# httpd as
    root initially and it will switch.  \n#\n# User/Group: The name (or #number) of
    the user/group to run httpd as.\n# It is usually good practice to create a dedicated
    user and group for\n# running httpd, as with most system services.\n#\nUser default\nGroup
    root\n\n# 'Main' server configuration\n#\n# The directives in this section set
    up the values used by the 'main'\n# server, which responds to any requests that
    aren't handled by a\n# <VirtualHost> definition.  These values also provide defaults
    for\n# any <VirtualHost> containers you may define later in the file.\n#\n# All
    of these directives may appear inside <VirtualHost> containers,\n# in which case
    these default settings will be overridden for the\n# virtual host being defined.\n#\n<VirtualHost
    *:80>\n    ServerName localhost\n    DocumentRoot /usr/local/apache2/htdocs\n\n
    \   <Directory \"/usr/local/apache2/htdocs\">\n        Options Indexes FollowSymLinks\n
    \       AllowOverride None\n        Require all granted\n    </Directory>\n\n
    \   RewriteEngine On\n    RewriteRule ^/reverseshellgenerator$ http://reverseshellgenerator:8080/
    [P]\n</VirtualHost>\n\n#\n# ServerAdmin: Your address, where problems with the
    server should be\n# e-mailed.  This address appears on some server-generated pages,
    such\n# as error documents.  e.g. admin@your-domain.com\n#\nServerAdmin root@localhost\n\n#\n#
    ServerName gives the name and port that the server uses to identify itself.\n#
    This can often be determined automatically, but we recommend you specify\n# it
    explicitly to prevent problems during startup.\n#\n# If your host doesn't have
    a registered DNS name, enter its IP address here.\n#\n#ServerName www.example.com:80\n\n#\n#
    Deny access to the entirety of your server's filesystem. You must\n# explicitly
    permit access to web content directories in other \n# <Directory> blocks below.\n#\n<Directory
    />\n    AllowOverride none\n    Require all denied\n</Directory>\n\n#\n# Note
    that from this point forward you must specifically allow\n# particular features
    to be enabled - so if something's not working as\n# you might expect, make sure
    that you have specifically enabled it\n# below.\n#\n\n#\n# DocumentRoot: The directory
    out of which you will serve your\n# documents. By default, all requests are taken
    from this directory, but\n# symbolic links and aliases may be used to point to
    other locations.\n#\nDocumentRoot \"/var/www/html\"\n\n#\n# Relax access to content
    within /var/www.\n#\n<Directory \"/var/www\">\n    AllowOverride None\n    # Allow
    open access:\n    Require all granted\n</Directory>\n\n# Further relax access
    to the default document root:\n<Directory \"/var/www/html\">\n    #\n    # Possible
    values for the Options directive are \"None\", \"All\",\n    # or any combination
    of:\n    #   Indexes Includes FollowSymLinks SymLinksifOwnerMatch ExecCGI MultiViews\n
    \   #\n    # Note that \"MultiViews\" must be named *explicitly* --- \"Options
    All\"\n    # doesn't give it to you.\n    #\n    # The Options directive is both
    complicated and important.  Please see\n    # http://httpd.apache.org/docs/2.4/mod/core.html#options\n
    \   # for more information.\n    #\n    Options Indexes FollowSymLinks\n\n    #\n
    \   # AllowOverride controls what directives may be placed in .htaccess files.\n
    \   # It can be \"All\", \"None\", or any combination of the keywords:\n    #
    \  Options FileInfo AuthConfig Limit\n    #\n    AllowOverride All\n\n    #\n
    \   # Controls who can get stuff from this server.\n    #\n    Require all granted\n</Directory>\n\n#\n#
    DirectoryIndex: sets the file that Apache will serve if a directory\n# is requested.\n#\n<IfModule
    dir_module>\n    DirectoryIndex index.html\n</IfModule>\n\n#\n# The following
    lines prevent .htaccess and .htpasswd files from being \n# viewed by Web clients.
    \n#\n<Files \".ht*\">\n    Require all denied\n</Files>\n\n#\n# ErrorLog: The
    location of the error log file.\n# If you do not specify an ErrorLog directive
    within a <VirtualHost>\n# container, error messages relating to that virtual host
    will be\n# logged here.  If you *do* define an error logfile for a <VirtualHost>\n#
    container, that host's errors will be logged there and not here.\n#\nErrorLog
    |/usr/bin/cat\n\n#\n# LogLevel: Control the number of messages logged to the error_log.\n#
    Possible values include: debug, info, notice, warn, error, crit,\n# alert, emerg.\n#\nLogLevel
    warn\n\n<IfModule log_config_module>\n    #\n    # The following directives define
    some format nicknames for use with\n    # a CustomLog directive (see below).\n
    \   #\n    LogFormat \"%h %l %u %t \\\"%r\\\" %>s %b \\\"%{Referer}i\\\" \\\"%{User-Agent}i\\\"\"
    combined\n    LogFormat \"%h %l %u %t \\\"%r\\\" %>s %b\" common\n\n    <IfModule
    logio_module>\n      # You need to enable mod_logio.c to use %I and %O\n      LogFormat
    \"%h %l %u %t \\\"%r\\\" %>s %b \\\"%{Referer}i\\\" \\\"%{User-Agent}i\\\" %I
    %O\" combinedio\n    </IfModule>\n\n    #\n    # The location and format of the
    access logfile (Common Logfile Format).\n    # If you do not define any access
    logfiles within a <VirtualHost>\n    # container, they will be logged here.  Contrariwise,
    if you *do*\n    # define per-<VirtualHost> access logfiles, transactions will
    be\n    # logged therein and *not* in this file.\n    #\n    #CustomLog \"logs/access_log\"
    common\n\n    #\n    # If you prefer a logfile with access, agent, and referer
    information\n    # (Combined Logfile Format) you can use the following directive.\n
    \   #\n    CustomLog |/usr/bin/cat combined\n</IfModule>\n\n<IfModule alias_module>\n
    \   #\n    # Redirect: Allows you to tell clients about documents that used to
    \n    # exist in your server's namespace, but do not anymore. The client \n    #
    will make a new request for the document at its new location.\n    # Example:\n
    \   # Redirect permanent /foo http://www.example.com/bar\n\n    #\n    # Alias:
    Maps web paths into filesystem paths and is used to\n    # access content that
    does not live under the DocumentRoot.\n    # Example:\n    # Alias /webpath /full/filesystem/path\n
    \   #\n    # If you include a trailing / on /webpath then the server will\n    #
    require it to be present in the URL.  You will also likely\n    # need to provide
    a <Directory> section to allow access to\n    # the filesystem path.\n\n    #\n
    \   # ScriptAlias: This controls which directories contain server scripts. \n
    \   # ScriptAliases are essentially the same as Aliases, except that\n    # documents
    in the target directory are treated as applications and\n    # run by the server
    when requested rather than as documents sent to the\n    # client.  The same rules
    about trailing \"/\" apply to ScriptAlias\n    # directives as to Alias.\n    #\n
    \   ScriptAlias /cgi-bin/ \"/var/www/cgi-bin/\"\n\n</IfModule>\n\n#\n# \"/var/www/cgi-bin\"
    should be changed to whatever your ScriptAliased\n# CGI directory exists, if you
    have that configured.\n#\n<Directory \"/var/www/cgi-bin\">\n    AllowOverride
    None\n    Options None\n    Require all granted\n</Directory>\n\n<IfModule mime_module>\n
    \   #\n    # TypesConfig points to the file containing the list of mappings from\n
    \   # filename extension to MIME-type.\n    #\n    TypesConfig /etc/mime.types\n\n
    \   #\n    # AddType allows you to add to or override the MIME configuration\n
    \   # file specified in TypesConfig for specific file types.\n    #\n    #AddType
    application/x-gzip .tgz\n    #\n    # AddEncoding allows you to have certain browsers
    uncompress\n    # information on the fly. Note: Not all browsers support this.\n
    \   #\n    #AddEncoding x-compress .Z\n    #AddEncoding x-gzip .gz .tgz\n    #\n
    \   # If the AddEncoding directives above are commented-out, then you\n    # probably
    should define those extensions to indicate media types:\n    #\n    AddType application/x-compress
    .Z\n    AddType application/x-gzip .gz .tgz\n\n    #\n    # AddHandler allows
    you to map certain file extensions to \"handlers\":\n    # actions unrelated to
    filetype. These can be either built into the server\n    # or added with the Action
    directive (see below)\n    #\n    # To use CGI scripts outside of ScriptAliased
    directories:\n    # (You will also need to add \"ExecCGI\" to the \"Options\"
    directive.)\n    #\n    #AddHandler cgi-script .cgi\n\n    # For type maps (negotiated
    resources):\n    #AddHandler type-map var\n\n    #\n    # Filters allow you to
    process content before it is sent to the client.\n    #\n    # To parse .shtml
    files for server-side includes (SSI):\n    # (You will also need to add \"Includes\"
    to the \"Options\" directive.)\n    #\n    AddType text/html .shtml\n    AddOutputFilter
    INCLUDES .shtml\n</IfModule>\n\n#\n# Specify a default charset for all content
    served; this enables\n# interpretation of all content as UTF-8 by default.  To
    use the \n# default browser choice (ISO-8859-1), or to allow the META tags\n#
    in HTML content to override this choice, comment out this\n# directive:\n#\nAddDefaultCharset
    UTF-8\n\n<IfModule mime_magic_module>\n    #\n    # The mod_mime_magic module
    allows the server to use various hints from the\n    # contents of the file itself
    to determine its type.  The MIMEMagicFile\n    # directive tells the module where
    the hint definitions are located.\n    #\n    MIMEMagicFile conf/magic\n</IfModule>\n\n#\n#
    Customizable error responses come in three flavors:\n# 1) plain text 2) local
    redirects 3) external redirects\n#\n# Some examples:\n#ErrorDocument 500 \"The
    server made a boo boo.\"\n#ErrorDocument 404 /missing.html\n#ErrorDocument 404
    \"/cgi-bin/missing_handler.pl\"\n#ErrorDocument 402 http://www.example.com/subscription_info.html\n#\n\n#\n#
    EnableMMAP and EnableSendfile: On systems that support it, \n# memory-mapping
    or the sendfile syscall may be used to deliver\n# files.  This usually improves
    server performance, but must\n# be turned off when serving from networked-mounted
    \n# filesystems or if support for these functions is otherwise\n# broken on your
    system.\n# Defaults if commented: EnableMMAP On, EnableSendfile Off\n#\n#EnableMMAP
    off\nEnableSendfile on\n\n# Supplemental configuration\n#\n# Load config files
    in the \"/etc/httpd/conf.d\" directory, if any.\nIncludeOptional conf.d/*.conf\n"
  index.html: "<!DOCTYPE html>\n<html>\n  <body>\n    <h1>My First 1 Heading !</h1>\n
    \   <h2>My Second 2 Heading</h2>\n    <h3>My Third 3 Heading</h3>\n    <p>My first
    paragraph</p>\n    <p>This is another paragraph.</p>\n    <br>\n    \n    <br>\n
    \   <a href=\"https://www.google.es\" target=\"_blank\" style=\"color: blue;\">This
    is a link external (Google.es)</a>\n    <br>\n    <a href=\"http://cyberchef-fernando0069-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com\"
    target=\"_blank\" style=\"color: blue;\">This is a link external (CyberChef)</a>\n
    \   <br>\n    <br>\n    <a href=\"http://reverseshellgenerator-fernando0069-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com\"
    target=\"_blank\" style=\"color: blue;\">This is a link internal (Reverse Shell
    Generator)</a>\n    <br>\n    <a href=\"http://wiki.ref-web.svc.cluster.local\"
    target=\"_blank\" style=\"color: blue;\">This is a link external (Wiki)</a>\n
    \   <br>\n  </body>\n</html>\n"
immutable: false
