apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: web
    app.kubernetes.io/component: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Values.name }}
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/part-of: ref-solutions
    layer: web
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: {{ .Values.version }}
    helm.sh/chart: {{ .Values.name }}-{{ .Values.appversion }}
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.name }}
        deployment: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: registry.access.redhat.com/ubi9/httpd-24:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8443
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html/index.html
          name: index-html
          readOnly: true
          subPath: index.html
        - mountPath: /etc/httpd/conf.d/00-virtualhost.conf
          name: virtualhost-conf
          subPath: 00-virtualhost.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: index.html
            path: index.html
          name: web
        name: index-html
      - configMap:
          defaultMode: 420
          items:
          - key: 00-virtualhost.conf
            path: 00-virtualhost.conf
          name: web
        name: virtualhost-conf
