apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/part-of: ref-solutions
    app.kubernetes.io/managed-by: Helm
    helm.chart-version: {{ .Chart.Name }}-{{ .Chart.Version }}
    helm.app-version: {{ .Chart.Name }}-{{ .Chart.AppVersion }}
    info.layer: {{ .Values.info.layer }} 
spec:
  replicas: {{ .Values.replica.min }}
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: {{ .Chart.Name }}
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: registry.access.redhat.com/ubi9/httpd-24:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8443
          protocol: TCP
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html/index.html
          name: index-html
          readOnly: true
          subPath: index.html
        - mountPath: /etc/httpd/conf.d/00-virtualhost.conf
          name: virtualhost-conf
          subPath: 00-virtualhost.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: index.html
            path: index.html
          name: web
        name: index-html
      - configMap:
          defaultMode: 420
          items:
          - key: 00-virtualhost.conf
            path: 00-virtualhost.conf
          name: web
        name: virtualhost-conf
