kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/part-of: ref-solutions
    app.kubernetes.io/managed-by: Helm
    info/helm/chart-version: {{ .Chart.Name }}-{{ .Chart.Version }}
    info/helm/app-version: {{ .Chart.Name }}-{{ .Chart.AppVersion }}
    info/layer: {{ .Values.info.layer }}
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name:  {{ .Chart.Name }}
      controller: true
      blockOwnerDeletion: true
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ .Chart.Name }}
    apiVersion: apps/v1
  minReplicas: {{ .Values.replica.min }}
  maxReplicas: {{ .Values.replica.max }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.metrics.utilization.cpu }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.metrics.utilization.mem }}
