kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/component: {{ .Chart.Name }}
    app.kubernetes.io/part-of: ref-solutions
    layer: {{ .Chart.Name }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ .Chart.Name }}
    apiVersion: apps/v1
  minReplicas: {{ .Values.replica.min }}
  maxReplicas: {{ .Values.replica.max }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.metrics.utilization.cpu }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.metrics.utilization.mem }}
