apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: fernando0069-dev
spec:
  rules:
  - host: web-fernando0069-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com
    http:
      paths:
      - path: /cyberchef
        pathType: Prefix
        backend:
          service:
            name: cyberchef
            port:
              number: 8080
      - path: /reverseshellgenerator
        pathType: Prefix
        backend:
          service:
            name: reverseshellgenerator
            port:
              number: 8080
      - path: /wiki
        pathType: Prefix
        backend:
          service:
            name: wiki-service
            port:
              number: 8080
