apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/part-of: ref-solutions
    app.kubernetes.io/managed-by: Helm
    helm.chart-version: {{ .Chart.Name }}-{{ .Chart.Version }}
    helm.app-version: {{ .Chart.Name }}-{{ .Chart.AppVersion }}
    info.layer: {{ .Values.info.layer }}
spec:
  minAvailable: {{ .Values.replica.min }}
  selector:
    matchLabels:
      deployment: {{ .Chart.Name }}
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
