apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    app.kubernetes.io/part-of: ref-solutions
    layer: tools
spec:
  minAvailable: {{ .Values.replica.min }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
