apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: {{ .Values.namespace }}
  labels:
    app: web
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: ref-solutions
    layer: web
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: web
  sessionAffinity: None
  type: ClusterIP
