apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: fernando0069-dev
  labels:
    app: db-gc
    app.kubernetes.io/component: dt100-gc
    app.kubernetes.io/part-of: ref-solutions
spec:
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  ports:
    - name: "postgres"
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: db-gc
