apiVersion: v1
kind: Service
metadata:
  name: web-gc
  namespace: fernando0069-dev
  labels:
    app: web-gc
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    app: web-gc
