apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
  annotations:
    uri-official: {{ .Values.annotations.uriofficial }}
spec:
  minAvailable: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
