kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.enviroment }}
    training: {{ .Values.training }}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      namespace: {{ .Values.namespace }}
      name: 'todo-html5:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'ubi9/httpd-24:latest'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/Fernando0069/my-charts.git'
      ref: main
    contextDir: charts/do180-todo-html5/
  triggers:
    - type: GitHub
      github:
        secret: 8ySggNExcksRWITmpP2R
    - type: Generic
      generic:
        secret: XgaK2wM_pNDdsQQolO8u
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
  runPolicy: Serial