# Default values for buildachart.
# This is a YAML-formatted file.

namespace: fernando0069-dev
name: the-gems-nodejs
labels:
  enviroment: pro
  layer: training
  training: DO180
replicaCount: 1
image: image-registry.openshift-image-registry.svc:5000/fernando0069-dev/the-gems-nodejs:latest
imagePullPolicy: Always
ports:
  http:
    name: http
    containerPort: 3000
    protocol: TCP
    servicePort: 8080
git:
  uri: 'https://github.com/Fernando0069/my-charts.git'
  ref: main
  contextDir: apps/do180-the-gems-nodejs/app/src
isfrom:
  name: 'nodejs:20-ubi9-minimal'