kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
    training: {{ .Values.labels.training }}
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: {{ .Values.ports.http.name }}
      protocol: {{ .Values.ports.http.protocol }}
      port: {{ .Values.ports.http.servicePort }}
      targetPort: {{ .Values.ports.http.containerPort }}
    - name: {{ .Values.ports.https.name }}
      protocol: {{ .Values.ports.https.protocol }}
      port: {{ .Values.ports.https.servicePort }}
      targetPort: {{ .Values.ports.https.containerPort }}
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: {{ .Values.name }}


























