apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: fernando0069-dev
  labels:
    app: web-{{ .Values.enviroment }}
    app.kubernetes.io/component: dt100-{{ .Values.enviroment }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web-{{ .Values.enviroment }}
  template:
    metadata:
      labels:
        app: web-{{ .Values.enviroment }}
    spec:
      hostname: web-{{ .Values.enviroment }}
      containers:
        - name: web-{{ .Values.enviroment }}
          image: {{ .Values.image.web }}
          env:
            - name: DbConnection
              value: Host=db-gc;Database=DT100;User ID=dt100;Password="001-Td"
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 50m
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
