apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db
  namesapce: fernando0069-dev
  labels:
    app: db-{{ .Values.enviroment }}
    app.kubernetes.io/component: dt100-{{ .Values.enviroment }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
