apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: fernando0069-dev
  labels:
    app: web-{{ .Values.enviroment }}
    app.kubernetes.io/component: dt100-{{ .Values.enviroment }}
spec:
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  ports:
    - name: "http"
      port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: web-{{ .Values.enviroment }}