apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.enviroment }}
    layer: {{ .Values.layer }}
spec:
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ .Chart.Name }}
    weight: 100
  wildcardPolicy: None
  selector:
    matchLabels:
      deployment: {{ .Chart.Name }}
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
