kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ .Values.asteroids.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.asteroids.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
    training: {{ .Values.labels.training }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: '{{ .Values.asteroids.name }}:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: {{ .Values.isfrom.name }}
  postCommit: {}
  source:
    type: Git
    git:
      uri: {{ .Values.git.uri }}
      ref: {{ .Values.git.ref }}
    contextDir: {{ .Values.asteroids.contextDir }}
  triggers:
    - type: GitHub
      github:
        secret: xv9w_dZ8xFEnGG9qgk4W
    - type: Generic
      generic:
        secret: tf5hesZmaZevLxAD3Jlz
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
  runPolicy: Serial
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ .Values.lunar-lander.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.lunar-lander.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
    training: {{ .Values.labels.training }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: '{{ .Values.asteroids.name }}:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: {{ .Values.isfrom.name }}
  postCommit: {}
  source:
    type: Git
    git:
      uri: {{ .Values.git.uri }}
      ref: {{ .Values.git.ref }}
    contextDir: {{ .Values.lunar-lander.contextDir }}
  triggers:
    - type: GitHub
      github:
        secret: xv9w_dZ8xFEnGG9qgk4W
    - type: Generic
      generic:
        secret: tf5hesZmaZevLxAD3Jlz
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
  runPolicy: Serial
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ .Values.snake.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.snake.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
    training: {{ .Values.labels.training }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: '{{ .Values.asteroids.name }}:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: {{ .Values.isfrom.name }}
  postCommit: {}
  source:
    type: Git
    git:
      uri: {{ .Values.git.uri }}
      ref: {{ .Values.git.ref }}
    contextDir: {{ .Values.snake.contextDir }}
  triggers:
    - type: GitHub
      github:
        secret: xv9w_dZ8xFEnGG9qgk4W
    - type: Generic
      generic:
        secret: tf5hesZmaZevLxAD3Jlz
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
  runPolicy: Serial
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ .Values.space-invaders.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.space-invaders.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
    training: {{ .Values.labels.training }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: '{{ .Values.asteroids.name }}:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: {{ .Values.isfrom.name }}
  postCommit: {}
  source:
    type: Git
    git:
      uri: {{ .Values.git.uri }}
      ref: {{ .Values.git.ref }}
    contextDir: {{ .Values.space-invaders.contextDir }}
  triggers:
    - type: GitHub
      github:
        secret: xv9w_dZ8xFEnGG9qgk4W
    - type: Generic
      generic:
        secret: tf5hesZmaZevLxAD3Jlz
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
  runPolicy: Serial
