kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: {{ .Values.asteroids.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.asteroids.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
    training: {{ .Values.labels.training }}
spec:
  lookupPolicy:
    local: false
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: {{ .Values.lunarlander.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.lunarlander.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
    training: {{ .Values.labels.training }}
spec:
  lookupPolicy:
    local: false
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: {{ .Values.snake.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.snake.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
    training: {{ .Values.labels.training }}
spec:
  lookupPolicy:
    local: false
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: {{ .Values.spaceinvaders.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.spaceinvaders.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
    training: {{ .Values.labels.training }}
spec:
  lookupPolicy:
    local: false
