kind: Route
apiVersion: route.openshift.io/v1
metadata:
metadata:
  name: {{ .Values.asteroids.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.asteroids.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
    training: {{ .Values.labels.training }}
spec:
  to:
    kind: Service
    name: {{ .Values.asteroids.name }}
    weight: 100
  port:
    targetPort: {{ .Values.ports.http.name }}
  tls:
    termination: edge
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
metadata:
  name: {{ .Values.lunar-lander.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.lunar-lander.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
    training: {{ .Values.labels.training }}
spec:
  to:
    kind: Service
    name: {{ .Values.lunar-lander.name }}
    weight: 100
  port:
    targetPort: {{ .Values.ports.http.name }}
  tls:
    termination: edge
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
metadata:
  name: {{ .Values.snake.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.snake.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
    training: {{ .Values.labels.training }}
spec:
  to:
    kind: Service
    name: {{ .Values.snake.name }}
    weight: 100
  port:
    targetPort: {{ .Values.ports.http.name }}
  tls:
    termination: edge
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
metadata:
  name: {{ .Values.space-invaders.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.space-invaders.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
    training: {{ .Values.labels.training }}
spec:
  to:
    kind: Service
    name: {{ .Values.space-invaders.name }}
    weight: 100
  port:
    targetPort: {{ .Values.ports.http.name }}
  tls:
    termination: edge
  wildcardPolicy: None
