# Default values for buildachart.
# This is a YAML-formatted file.

namespace: fernando0069-dev
enviroment: gc
replicaCount: 1
image:
  db: registry.access.redhat.com/rhel9/postgresql-16:latest
  web: nginx
  pullPolicy: Always
resources:
   limits:
     db:
       cpu: 100m
       memory: 1Gi
     web:
       cpu: 50m
       memory: 512Mi
   requests:
     db:
       cpu: 30m
       memory: 128Mi
     web:
       cpu: 15m
       memory: 128Mi
