# Default values for buildachart.
# This is a YAML-formatted file.

namespace: fernando0069-dev
name: web-status
labels:
  enviroment: pro
  layer: tools
replicaCount: 1
image: docker.io/fernando0069/web-spectral:latest
imagePullPolicy: Always
ports:
  http:
    name: http
    containerPort: 8080
    protocol: TCP
    servicePort: 8080
git:
  uri: 'https://github.com/Fernando0069/my-charts.git'
  ref: main
  contextDir: charts/web-status/files