apiVersion: v1
kind: Secret
metadata:
  name: reverseshellgenerator-generic-webhook
  namespace: {{ .Value.namespace }}
  labels:
    app: reverseshellgenerator
    app.kubernetes.io/component: {{ .Value.name }}
    layer: tools
type: Opaque
data:
  WebHookSecretKey: OTY0NzUwMWQxY2U4ZWIwZg==
