apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.enviroment }}
    training: {{ .Values.training }}
data:
  app.js: |
    var express = require('express');
    app = express();
    
    app.get('/', function (req, res) {
      res.send('Hello World!');
    });
    
    app.listen(8080, function () {
      console.log('Example app listening on port 8080!');
    });
  package.json: |
    {
      "name": "nodejs-helloworld",
      "version": "1.0.0",
      "description": "Hello World!",
      "main": "app.js",
      "author": "Red Hat Training",
      "license": "ASL",
      "dependencies": {
        "express": "4.14.x"
      },
      "scripts": {
        "start": "node app.js"
      }
    }
immutable: false
