kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.enviroment }}
    training: {{ .Values.training }}
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: {{ .Values.name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: {{ .Values.name }}
    spec:
      containers:
        - name:  {{ .Values.name }}
          image: {{ .Values.image }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          volumeMounts:
          - name: app-js
            mountPath: /opt/app-root/src/app.js
            readOnly: true
            subPath: app.js
          - name: package-json
            mountPath: /opt/app-root/src/package.json
            readOnly: true
            subPath: package.json
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      volumes:
      - name: app-js
        configMap:
          name: {{ .Values.name }}
          items:
            - key: app.js
              path: app.js
          defaultMode: 420
      - name: package-json
        configMap:
          name: {{ .Values.name }}
          items:
            - key: package.json
              path: package.json
          defaultMode: 420
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
