apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.enviroment }}
    training: {{ .Values.training }}
spec:
  to:
    kind: Service
    name: {{ .Values.name }}
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
  tls:
    termination: edge