apiVersion: v1
kind: Secret
metadata:
  name: reverseshellgenerator-github-webhook
  namespace: {{ .Value.namespace }}
  labels:
    app: reverseshellgenerator
    app.kubernetes.io/component: {{ .Value.name }}
    layer: tools
type: Opaque
data:
  WebHookSecretKey: NDc1OTZmZWFhY2NhMGM3Mg==
