kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
    training: {{ .Values.labels.training }}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.name }}:latest
      namespace: {{ .Values.namespace }}
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'php:8.1-ubi9'
  postCommit: {}
  source:
    type: Git
    git:
      uri: {{ .Values.git.uri }}
      ref: {{ .Values.git.ref }}
    contextDir: {{ .Values.git.contextDir }}
  triggers:
    - type: GitHub
      github:
        secret: 8ySggNEGcksRWIsmpP2R
    - type: Generic
      generic:
        secret: XgaK2wM_YNDdsQUolO8u
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
  runPolicy: Serial