apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.enviroment }}
    training: {{ .Values.training }}
data:
  index.php: |
    <?php
      print "Hello, World! php version is " . PHP_VERSION . "\n";
      print "\n";
    ?>
  phpinfo.php: |
    <?php
      // Show all information, defaults to INFO_ALL
      phpinfo();
      // Show just the module information, phpinfo(8) yields identical results.
      phpinfo(INFO_MODULES);
    ?>
immutable: false
