# Default values for buildachart.
# This is a YAML-formatted file.

namespace: fernando0069-dev
name: game-off-2012
labels:
  enviroment: pro
  layer: training
  training: DO180
replicaCount: 1
image: image-registry.openshift-image-registry.svc:5000/fernando0069-dev/openshift-helloworld:latest
imagePullPolicy: Always
ports:
  http:
    name: http
    containerPort: 8080
    protocol: TCP
    servicePort: 8080
  https:
    name: https
    containerPort: 8443
    protocol: TCP
    servicePort: 8443
git:
  uri: 'https://github.com/Fernando0069/my-charts.git'
  ref: main
  contextDir: charts/do180-game-off-2012/files