kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
    training: {{ .Values.labels.training }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: openshift-helloworld
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openshift-helloworld
    spec:
      containers:
        - name: openshift-helloworld
          image: 'image-registry.openshift-image-registry.svc:5000/fernando0069-dev/openshift-helloworld@sha256:08bfc0e01b53e9b5b4dbcc1df52565f74b861a886f0b337678f358729edb5eb8'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: {{ .Values.imagePullPolicy }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
