kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: '{{ .Values.name }}-8080'
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
    training: {{ .Values.labels.training }}
spec:
  to:
    kind: Service
    name: '{{ .Values.name }}-8080'
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
