kind: Service
apiVersion: v1
metadata:
  name: '{{ .Values.name }}-8080'
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
    training: {{ .Values.labels.training }}
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: {{ .Values.ports.http-8080.name }}
      port: {{ .Values.ports.http-8080.servicePort }}
      protocol: {{ .Values.ports.http-8080.protocol }}
      targetPort: {{ .Values.ports.http-8080.containerPort }}
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: {{ .Values.name }}