# Default values for buildachart.
# This is a YAML-formatted file.

namespace: fernando0069-dev
name: nodejs-app
enviroment: training
training: DO180
replicaCount: 1
image: image-registry.openshift-image-registry.svc:5000/fernando0069-dev/nodejs-app:latest
ports:
  name: http
  http: 8080
resources:
  limits:
    cpu: 20m
    memory: 64Mi
  requests:
    cpu: 5m
    memory: 32Mi
startupProbe:
  initialDelaySeconds: 15