# Default values for buildachart.
# This is a YAML-formatted file.

namespace: fernando0069-dev
name: reverseshellgenerator
enviroment: gc
layer: tools
replicaCount: 1
image: image-registry.openshift-image-registry.svc:5000/fernando0069-dev/reverseshellgenerator:latest
resources:
  limits:
    db:
      cpu: 100m
      memory: 1Gi
    web:
      cpu: 50m
      memory: 512Mi
  requests:
    db:
      cpu: 30m
      memory: 128Mi
    web:
      cpu: 15m
      memory: 128Mi