kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.enviroment }}
    training: {{ .Values.training }}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      namespace: {{ .Values.namespace }}
      name: 'nodejs-helloworld:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:20-ubi9'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/Fernando0069/my-charts.git'
      ref: main
    contextDir: charts/do180-nodejs-helloworld/files
  triggers:
    - type: GitHub
      github:
        secret: jX94w5Tp6qeOyRfwkjrC
    - type: Generic
      generic:
        secret: HddC9vY9Z05Qu9R9Xmxf
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
  runPolicy: Serial
