apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-github-webhook
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
type: Opaque
data:
  WebHookSecretKey: NDc1OTZmZWFhY2NhMGM3Mg==
