# Default values for buildachart.
# This is a YAML-formatted file.

namespace: fernando0069-dev
name: php-temperature-cm
labels:
  enviroment: pro
  layer: training
  training: DO180
replicaCount: 1
image: image-registry.openshift-image-registry.svc:5000/fernando0069-dev/php-temperature:latest
imagePullPolicy: Always
ports:
  http:
    name: http
    containerPort: 8080
    protocol: TCP
    servicePort: 8080
  https:
    name: https
    containerPort: 8443
    protocol: TCP
    servicePort: 8443
resources:
  limits:
    cpu: 10m
    memory: 64Mi
  requests:
    cpu: 5m
    memory: 32Mi
