# Default values for buildachart.
# This is a YAML-formatted file.

namespace: fernando0069-dev
name: retro-games
labels:
  enviroment: pro
  layer: training
  training: DO180
replicaCount: 1
imagePullPolicy: Always
ports:
  http:
    name: http
    containerPort: 8080
    protocol: TCP
    servicePort: 8080
  https:
    name: https
    containerPort: 8443
    protocol: TCP
    servicePort: 8443
resources:
  limits:
    cpu: 10m
    memory: 64Mi
  requests:
    cpu: 5m
    memory: 32Mi
git:
  uri: 'https://github.com/Fernando0069/my-charts.git'
  ref: main
asteroids:
  name: retro-games-asteroids
  image: image-registry.openshift-image-registry.svc:5000/fernando0069-dev/retro-games-asteroids:latest
  contextDir: apps/do180-retro-games/app/src/asteroids/
lunar-lander:
  name: retro-games-lunar-lander
  image: image-registry.openshift-image-registry.svc:5000/fernando0069-dev/retro-games-lunar-lander:latest
  contextDir: apps/do180-retro-games/app/src/lunar-lander/
snake:
  name: retro-games-snake
  image: image-registry.openshift-image-registry.svc:5000/fernando0069-dev/retro-games-snake:latest
  contextDir: apps/do180-retro-games/app/src/snake/
space-invaders:
  name: retro-games-space-invaders
  image: image-registry.openshift-image-registry.svc:5000/fernando0069-dev/retro-games-space-invaders:latest
  contextDir: apps/do180-retro-games/app/src/space-invaders/
isfrom:
  name: 'httpd:2.4-ubi9'