kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
    training: {{ .Values.labels.training }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: '{{ .Values.name }}:latest'
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'golang:1.18-ubi8'
  source:
    type: Git
    git:
      uri: {{ .Values.git.uri }}
      ref: {{ .Values.git.ref }}
    contextDir: {{ .Values.git.contextDir }}
  triggers:
    - type: GitHub
      github:
        secret: c7POrccbfFNqkU_UNREP
    - type: Generic
      generic:
        secret: lwojglAUy4lmSS8Wbe-Z
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
  runPolicy: Serial
