apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
spec:
  failedBuildsHistoryLimit: 5
  successfulBuildsHistoryLimit: 5
  nodeSelector: null
  postCommit: {}
  runPolicy: Serial
  resources: {}
  source:
    type: Git
    git:
      uri: {{ .Values.git.uri }}
      ref: {{ .Values.git.ref }}
    contextDir: {{ .Values.git.contextDir }}
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.name }}:latest
      namespace: {{ .Values.namespace }}
  triggers:
    - type: GitHub
      github:
        secret: 7ySggNExRksRWITmpP2R
    - type: Generic
      generic:
        secret: XgDK2wM_pNDdsQQolO7u
    - type: ConfigChange
