apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.labels.enviroment }}
    layer: {{ .Values.labels.layer }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: {{ .Values.ports.http.name }}
    port: {{ .Values.ports.http.servicePort }}
    protocol: {{ .Values.ports.http.protocol }}
    targetPort: {{ .Values.ports.http.containerPort }}
  selector:
    app: {{ .Values.name }}
  sessionAffinity: None
  type: ClusterIP
