apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-war-ear-pipeline
spec:
  params:
    - default: Fernando
      name: git-user
      type: string
    - default: fernando0069@gmail.com
      name: git-email
      type: string
  tasks:
    - name: clone-repo
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build-war
      runAfter:
        - clone-repo
      taskRef:
        kind: Task
        name: build-war
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build-ear
      runAfter:
        - build-war
      taskRef:
        kind: Task
        name: build-ear
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: git-push
      params:
        - name: git-user
          value: $(params.git-user)
        - name: git-email
          value: $(params.git-email)
      runAfter:
        - build-ear
      taskRef:
        kind: Task
        name: git-push
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace