kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.enviroment }}
    training: {{ .Values.training }}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      namespace: fernando0069-dev
      name: 'php-helloworld:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'php:8.1-ubi9'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/Fernando0069/my-charts.git'
      ref: main
    contextDir: charts/do180-php-helloworld/files
  runPolicy: Serial
  triggers:
    - type: GitHub
      github:
        secret: 9SYMeM3lKyNbQJN6mNO2
    - type: Generic
      generic:
        secret: hmfbqL7Xj5W-tIA70zKv
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
  runPolicy: Serial
