kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.enviroment }}
    training: {{ .Values.training }}
data:
  index.php: |
    <?php
    print "Hello, World! php version is " . PHP_VERSION . "\n";
    print "\n";
    print "Today is going to be a great day.";
    ?>
