kind: Deployment
apiVersion: apps/v1
metadata:
  name: php-helloworld
  namespace: fernando0069-dev
  labels:
    app: php-helloworld
    app.kubernetes.io/component: php-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: php-helloworld
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: php-helloworld
    spec:
      containers:
        - name: php-helloworld
          image: 'image-registry.openshift-image-registry.svc:5000/fernando0069-dev/php-helloworld@sha256:44de748e3be4ba59719d6d0d2a39582f5937783469738cc5f6d6e289fca37930'
          ports:
            - name http
              containerPort: 8080
              protocol: TCP
            - name https
              containerPort: 8443
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /var/www/html/index.php
            name: index-php
            readOnly: true
            subPath: index.php
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: index-php
        configMap:
          defaultMode: 420
          items:
          - key: index.php
            path: index.php
          name: web
        
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600