apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: php-helloworld
  namespace: {{ .Value.namespace }}
  labels:
    app: php-helloworld
    app.kubernetes.io/component: php-helloworld
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: php-helloworld
