apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: php-helloworld
  namespace: {{ .Value.namespace }}
  labels:
    app: php-helloworld
    app.kubernetes.io/component: do180
    layer: tools
spec:
  to:
    kind: Service
    name: php-helloworld
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
