apiVersion: v1
kind: Service
metadata:
  name: php-helloworld
  namespace: {{ .Value.namespace }}
  labels:
    app: php-helloworld
    app.kubernetes.io/component: do180
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deployment: php-helloworld