# Default values for buildachart.
# This is a YAML-formatted file.

namespace: fernando0069-dev
name: openshift-helloworld
labels:
  enviroment: pro
  layer: training
  training: DO180
replicaCount: 1
image: image-registry.openshift-image-registry.svc:5000/fernando0069-dev/openshift-helloworld:latest
imagePullPolicy: Always
ports:
  http8080:
    name: http-8080
    containerPort: 8080
    protocol: TCP
    servicePort: 8080
  http8888:
    name: http-8888
    containerPort: 8888
    protocol: TCP
    servicePort: 8888
git:
  uri: 'https://github.com/Fernando0069/my-charts.git'
  ref: main
  contextDir: apps/do180-openshift-helloworld/apps/src/