kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/component: {{ .Values.name }}
    enviroment: {{ .Values.enviroment }}
    layer: {{ .Values.layer }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: {{ .Values.ports.name }}
    port: {{ .Values.ports.servicePort }}
    protocol: {{ .Values.ports.protocol }}
    targetPort: {{ .Values.ports.containerPort }}
  selector:
    app: {{ .Values.name }}
  sessionAffinity: None
  type: ClusterIP
